name: h5pyd tests

on: pull_request

env:
  AWS_S3_NO_SIGN_REQUEST: 1
  AWS_S3_GATEWAY: http://s3.us-west-2.amazonaws.com
  BUCKET_NAME: nrel-pds-hsds
  HS_ENDPOINT: http://localhost:5101

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]
        include:
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: 3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,hsds]

      - name: Start HSDS and run tests
        shell: bash
        run: |
          hsds & # run hsds local server in background
          sleep 11 # let the nodes get ready
          pytest -v tests/h5pyd_tests.py
